#### Set the table indizes for the PK-Sim expression data base ####
INDIZES <- c(
  "CREATE INDEX expression_data_properties_i1 ON tab_expression_data_properties(property,property_value)",
  "CREATE UNIQUE INDEX expression_data_records_i1 ON tab_expression_data_records(data_base,data_base_rec_id)",
  "CREATE INDEX expression_data_records_i2 ON tab_expression_data_records(gender)",
  "CREATE INDEX expression_data_records_i3 ON tab_expression_data_records(tissue)",
  "CREATE INDEX expression_data_records_i4 ON tab_expression_data_records(health_state)",
  "CREATE INDEX expression_data_records_i5 ON tab_expression_data_records(sample_source)",
  "CREATE INDEX expression_data_records_i6 ON tab_expression_data_records(age_id)",
  "CREATE INDEX gene_variants_i1 ON tab_gene_variants(variant_name)",
  "CREATE INDEX ri_expression_data_age_properties_1 ON tab_expression_data_age_properties(age_id)",
  "CREATE INDEX ri_expression_data_gender_properties_1 ON tab_expression_data_gender_properties(gender)",
  "CREATE INDEX ri_expression_data_health_state_properties_1 ON tab_expression_data_health_state_properties(health_state)",
  "CREATE INDEX ri_expression_data_properties_1 ON tab_expression_data_properties(data_source_id)",
  "CREATE INDEX ri_expression_data_records_1 ON tab_expression_data_records(data_base)",
  "CREATE INDEX ri_expression_data_sample_source_properties_1 ON tab_expression_data_sample_source_properties(sample_source)",
  "CREATE INDEX ri_expression_data_tissue_properties_1 ON tab_expression_data_tissue_properties(tissue)",
  "CREATE INDEX ri_expression_data_values_1 ON tab_expression_data_values(variant_id)",
  "CREATE INDEX ri_expression_data_values_3 ON tab_expression_data_values(data_source_id)",
  "CREATE INDEX ri_gene_names_1 ON tab_gene_names(gene_id)",
  "CREATE INDEX ri_gene_names_2 ON tab_gene_names(name_type)",
  "CREATE INDEX ri_gene_variants_1 ON tab_gene_variants(gene_id)",
  "CREATE INDEX tab_expression_data_unitstab_expression_data_values ON tab_expression_data_values(unit)")

#### Set the Views  for the PK-Sim expression data base (enables quick result generation) ####
VIEW <- c("CREATE VIEW QRY_CONTAINER_TISSUE AS SELECT TAB_CONTAINER_TISSUE.CONTAINER as CONTAINER, TAB_CONTAINER_TISSUE.TISSUE as TISSUE FROM TAB_CONTAINER_TISSUE",
          "CREATE VIEW QRY_COUNT_GENES AS SELECT Count(TAB_GENES.GENE_ID) AS CountOfGENE_ID FROM TAB_GENES",
          "CREATE VIEW QRY_COUNT_VALUES AS SELECT Count(TAB_EXPRESSION_DATA_VALUES.VARIANT_ID) AS CountOfVARIANT_ID FROM TAB_EXPRESSION_DATA_VALUES",
          "CREATE VIEW QRY_COUNT_VARIANTS AS SELECT Count(TAB_GENE_VARIANTS.VARIANT_ID) AS CountOfVARIANT_ID FROM TAB_GENE_VARIANTS",
          "CREATE VIEW QRY_GENDER_HINT AS SELECT TAB_EXPRESSION_DATA_GENDERS.GENDER, TAB_EXPRESSION_DATA_GENDERS.INFORMATION FROM TAB_EXPRESSION_DATA_GENDERS",
          "CREATE VIEW QRY_HEALTH_STATE_HINT AS SELECT TAB_EXPRESSION_DATA_HEALTH_STATE.HEALTH_STATE, TAB_EXPRESSION_DATA_HEALTH_STATE.INFORMATION FROM TAB_EXPRESSION_DATA_HEALTH_STATE",
          "CREATE VIEW QRY_NAME_TYPE_HINT AS SELECT TAB_GENE_NAME_TYPES.NAME_TYPE, TAB_GENE_NAME_TYPES.INFORMATION FROM TAB_GENE_NAME_TYPES",
          "CREATE VIEW QRY_SAMPLE_SOURCE_HINT AS SELECT TAB_EXPRESSION_DATA_SAMPLE_SOURCES.SAMPLE_SOURCE, TAB_EXPRESSION_DATA_SAMPLE_SOURCES.INFORMATION FROM TAB_EXPRESSION_DATA_SAMPLE_SOURCES",
          "CREATE VIEW QRY_TISSUE_HINT AS SELECT TAB_EXPRESSION_DATA_TISSUES.TISSUE, TAB_EXPRESSION_DATA_TISSUES.INFORMATION FROM TAB_EXPRESSION_DATA_TISSUES",
          "CREATE VIEW QRY_UNIT_HINT AS SELECT TAB_EXPRESSION_DATA_UNITS.UNIT, TAB_EXPRESSION_DATA_UNITS.INFORMATION FROM TAB_EXPRESSION_DATA_UNITS")

#### List of tables and their creation & update SQL statements ####
# list data base table creation commands with additional information on variables and connections
CREATE_TBALES <- data.frame(TABLE <- c("tab_container_tissue",
                                       "tab_dts_properties",
                                       "tab_expression_data_age_properties",
                                       "tab_expression_data_ages",
                                       "tab_expression_data_bases",
                                       "tab_expression_data_gender_properties",
                                       "tab_expression_data_genders",
                                       "tab_expression_data_health_state",
                                       "tab_expression_data_health_state_properties",
                                       "tab_expression_data_properties",
                                       "tab_expression_data_records",
                                       "tab_expression_data_sample_source_properties",
                                       "tab_expression_data_sample_sources",
                                       "tab_expression_data_tissue_properties",
                                       "tab_expression_data_tissues",
                                       "tab_expression_data_units",
                                       "tab_expression_data_values",
                                       "tab_gene_name_types",
                                       "tab_gene_names",
                                       "tab_gene_variants",
                                       "tab_genes",
                                       "tab_global_statistics"),
                            COMMAND <- c("CREATE TABLE tab_container_tissue ( container text NOT NULL, tissue text NULL )", 
                                         "CREATE TABLE tab_dts_properties ( table_name text NOT NULL, column_name text NOT NULL, german text NULL, english text NULL, tooltip_german text NULL, tooltip_english text NULL, dimension_type text NULL, hidden bigint NOT NULL DEFAULT 0, editable bigint NOT NULL DEFAULT 1, PRIMARY KEY(table_name, column_name) )", 
                                         "CREATE TABLE tab_expression_data_age_properties ( age_id bigint NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(age_id, property, property_value), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )", 
                                         "CREATE TABLE tab_expression_data_ages ( age_id bigint NOT NULL, age_min double, age_max double, age_mean double, age_median double, PRIMARY KEY (age_id) )", "CREATE TABLE tab_expression_data_bases ( data_base text NOT NULL, url text NOT NULL, PRIMARY KEY(data_base) )",
                                         #"CREATE TABLE tab_expression_data_ages ( age_id bigint NOT NULL, age_value text, PRIMARY KEY (age_id) )", "CREATE TABLE tab_expression_data_bases ( data_base text NOT NULL, url text NOT NULL, PRIMARY KEY(data_base) )", 
                                         "CREATE TABLE tab_expression_data_gender_properties ( gender text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(gender, property, property_value), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender) )", 
                                         "CREATE TABLE tab_expression_data_genders ( gender text NOT NULL, information text NOT NULL, PRIMARY KEY(gender) )", 
                                         "CREATE TABLE tab_expression_data_health_state ( health_state text NOT NULL, information text NOT NULL, PRIMARY KEY(health_state) )", 
                                         "CREATE TABLE tab_expression_data_health_state_properties ( health_state text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(health_state, property, property_value), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state) )", 
                                         "CREATE TABLE tab_expression_data_properties ( data_source_id bigint NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(data_source_id, property), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id) )", 
                                         "CREATE TABLE tab_expression_data_records ( data_source_id bigint NOT NULL, data_base text NOT NULL, data_base_rec_id text NULL, last_refresh_date text NOT NULL, gender text NULL, tissue text NULL, health_state text NULL, sample_source text NULL, age_id bigint NULL, PRIMARY KEY(data_source_id), FOREIGN KEY(data_base) REFERENCES tab_expression_data_bases(data_base), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )", 
                                         "CREATE TABLE tab_expression_data_sample_source_properties ( sample_source text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(sample_source, property, property_value), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source) )", 
                                         "CREATE TABLE tab_expression_data_sample_sources ( sample_source text NOT NULL, information text NOT NULL, PRIMARY KEY(sample_source) )", 
                                         "CREATE TABLE tab_expression_data_tissue_properties ( tissue text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(tissue, property, property_value), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue) )", 
                                         "CREATE TABLE tab_expression_data_tissues ( tissue text NOT NULL, information text NOT NULL, PRIMARY KEY(tissue) )", 
                                         "CREATE TABLE tab_expression_data_units ( unit text NOT NULL, information text NOT NULL, PRIMARY KEY(unit) )", 
                                         "CREATE TABLE tab_expression_data_values ( variant_id bigint NOT NULL, data_source_id bigint NOT NULL, sample_count double NOT NULL, total_count double NOT NULL, unit text NOT NULL, PRIMARY KEY(variant_id, data_source_id), FOREIGN KEY(variant_id) REFERENCES tab_gene_variants(variant_id), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id), FOREIGN KEY(unit) REFERENCES tab_expression_data_units(unit) )", 
                                         "CREATE TABLE tab_gene_name_types ( name_type text NOT NULL, information text NOT NULL, PRIMARY KEY(name_type) )", 
                                         "CREATE TABLE tab_gene_names ( gene_id bigint NOT NULL, gene_name text NOT NULL, name_type text NOT NULL, PRIMARY KEY(gene_id, gene_name, name_type), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id), FOREIGN KEY(name_type) REFERENCES tab_gene_name_types(name_type) )", 
                                         "CREATE TABLE tab_gene_variants ( variant_id bigint NOT NULL, variant_name text NOT NULL, gene_id bigint NOT NULL, PRIMARY KEY(variant_id), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id) )", 
                                         "CREATE TABLE tab_genes ( gene_id bigint NOT NULL, PRIMARY KEY(gene_id) )", 
                                         "CREATE TABLE tab_global_statistics ( unit text NULL, 'avg' double NULL )"
                            ),
                            ALTER_COMMAND = c("ALTER TABLE tab_container_tissue ( container text NOT NULL, tissue text NULL )", 
                                              "ALTER TABLE tab_dts_properties ( table_name text NOT NULL, column_name text NOT NULL, german text NULL, english text NULL, tooltip_german text NULL, tooltip_english text NULL, dimension_type text NULL, hidden bigint NOT NULL DEFAULT 0, editable bigint NOT NULL DEFAULT 1, PRIMARY KEY(table_name, column_name) )", 
                                              "ALTER TABLE tab_expression_data_age_properties ( age_id bigint NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(age_id, property, property_value), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )", 
                                              "ALTER TABLE tab_expression_data_ages ( age_id bigint NOT NULL, age_min double, age_max double, age_mean double, age_median double, PRIMARY KEY (age_id) )", "ALTER TABLE tab_expression_data_bases ( data_base text NOT NULL, url text NOT NULL, PRIMARY KEY(data_base) )",
                                              #"ALTER TABLE tab_expression_data_ages ( age_id bigint NOT NULL, age_value text, PRIMARY KEY (age_id) )", "ALTER TABLE tab_expression_data_bases ( data_base text NOT NULL, url text NOT NULL, PRIMARY KEY(data_base) )", 
                                              "ALTER TABLE tab_expression_data_gender_properties ( gender text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(gender, property, property_value), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender) )", 
                                              "ALTER TABLE tab_expression_data_genders ( gender text NOT NULL, information text NOT NULL, PRIMARY KEY(gender) )", 
                                              "ALTER TABLE tab_expression_data_health_state ( health_state text NOT NULL, information text NOT NULL, PRIMARY KEY(health_state) )", 
                                              "ALTER TABLE tab_expression_data_health_state_properties ( health_state text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(health_state, property, property_value), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state) )", 
                                              "ALTER TABLE tab_expression_data_properties ( data_source_id bigint NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(data_source_id, property), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id) )", 
                                              "ALTER TABLE tab_expression_data_records ( data_source_id bigint NOT NULL, data_base text NOT NULL, data_base_rec_id text NULL, last_refresh_date text NOT NULL, gender text NULL, tissue text NULL, health_state text NULL, sample_source text NULL, age_id bigint NULL, PRIMARY KEY(data_source_id), FOREIGN KEY(data_base) REFERENCES tab_expression_data_bases(data_base), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )", 
                                              "ALTER TABLE tab_expression_data_sample_source_properties ( sample_source text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(sample_source, property, property_value), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source) )", 
                                              "ALTER TABLE tab_expression_data_sample_sources ( sample_source text NOT NULL, information text NOT NULL, PRIMARY KEY(sample_source) )", 
                                              "ALTER TABLE tab_expression_data_tissue_properties ( tissue text NOT NULL, property text NOT NULL, property_value text NOT NULL, PRIMARY KEY(tissue, property, property_value), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue) )", 
                                              "ALTER TABLE tab_expression_data_tissues ( tissue text NOT NULL, information text NOT NULL, PRIMARY KEY(tissue) )", 
                                              "ALTER TABLE tab_expression_data_units ( unit text NOT NULL, information text NOT NULL, PRIMARY KEY(unit) )", 
                                              "ALTER TABLE tab_expression_data_values ( variant_id bigint NOT NULL, data_source_id bigint NOT NULL, sample_count double NOT NULL, total_count double NOT NULL, unit text NOT NULL, PRIMARY KEY(variant_id, data_source_id), FOREIGN KEY(variant_id) REFERENCES tab_gene_variants(variant_id), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id), FOREIGN KEY(unit) REFERENCES tab_expression_data_units(unit) )", 
                                              "ALTER TABLE tab_gene_name_types ( name_type text NOT NULL, information text NOT NULL, PRIMARY KEY(name_type) )", 
                                              "ALTER TABLE tab_gene_names ( gene_id bigint NOT NULL, gene_name text NOT NULL, name_type text NOT NULL, PRIMARY KEY(gene_id, gene_name, name_type), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id), FOREIGN KEY(name_type) REFERENCES tab_gene_name_types(name_type) )", 
                                              "ALTER TABLE tab_gene_variants ( variant_id bigint NOT NULL, variant_name text NOT NULL, gene_id bigint NOT NULL, PRIMARY KEY(variant_id), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id) )", 
                                              "ALTER TABLE tab_genes ( gene_id bigint NOT NULL, PRIMARY KEY(gene_id) )", 
                                              "ALTER TABLE tab_global_statistics ( unit text NULL, 'avg' double NULL )")
)

#### List of tables and their column properties  ####

TAB_s <- c(
  "tab_container_tissue",
  "tab_dts_properties",
  "tab_expression_data_age_properties",
  "tab_expression_data_ages",
  "tab_expression_data_bases",
  "tab_expression_data_gender_properties",
  "tab_expression_data_genders",
  "tab_expression_data_health_state",
  "tab_expression_data_health_state_properties",
  "tab_expression_data_properties",
  "tab_expression_data_records",
  "tab_expression_data_sample_source_properties",
  "tab_expression_data_sample_sources",
  "tab_expression_data_tissue_properties",
  "tab_expression_data_tissues",
  "tab_expression_data_units",
  "tab_expression_data_values",
  "tab_gene_name_types",
  "tab_gene_names",
  "tab_gene_variants",
  "tab_genes",
  "tab_global_statistics") 
TYPE <- list(
  c("text" , "text"),
  c("text"  , "text" , "text" , "text" , "text", "text", "text", "bigint", "bigint"),
  c("bigint", "text", "text"),
  c("bigint", "text","double", "double", "double", "double"),
  #c("bigint", "text", "text"), # tab_expression_data_ages
  c("text", "text"), 
  c("text", "text", "text"),
  c("text", "text"),
  c("text", "text"),
  c("text", "text", "text"),
  c("bigint", "text", "text"),
  c("bigint", "text", "text", "text", "text", "text", "text", "text", "bigint"),
  c("text", "text", "text"),
  c("text", "text"),
  c("text", "text", "text"),
  c("text", "text"),
  c("text", "text"),
  c("bigint", "bigint", "double", "double", "text"),
  c("text", "text"),
  c("bigint", "text", "text"),
  c("bigint", "text", "bigint"),
  c("bigint"),
  c("text", "double") )
