#### Set the table indizes for the PK-Sim expression data base ####
INDIZES <- c(
  "CREATE INDEX expression_data_properties_i1 ON tab_expression_data_properties(property,property_value)",
  "CREATE UNIQUE INDEX expression_data_records_i1 ON tab_expression_data_records(data_base,data_base_rec_id)",
  "CREATE INDEX expression_data_records_i2 ON tab_expression_data_records(gender)",
  "CREATE INDEX expression_data_records_i3 ON tab_expression_data_records(tissue)",
  "CREATE INDEX expression_data_records_i4 ON tab_expression_data_records(health_state)",
  "CREATE INDEX expression_data_records_i5 ON tab_expression_data_records(sample_source)",
  "CREATE INDEX expression_data_records_i6 ON tab_expression_data_records(age_id)",
  "CREATE INDEX gene_variants_i1 ON tab_gene_variants(variant_name)",
  "CREATE INDEX ri_expression_data_age_properties_1 ON tab_expression_data_age_properties(age_id)",
  "CREATE INDEX ri_expression_data_gender_properties_1 ON tab_expression_data_gender_properties(gender)",
  "CREATE INDEX ri_expression_data_health_state_properties_1 ON tab_expression_data_health_state_properties(health_state)",
  "CREATE INDEX ri_expression_data_properties_1 ON tab_expression_data_properties(data_source_id)",
  "CREATE INDEX ri_expression_data_records_1 ON tab_expression_data_records(data_base)",
  "CREATE INDEX ri_expression_data_sample_source_properties_1 ON tab_expression_data_sample_source_properties(sample_source)",
  "CREATE INDEX ri_expression_data_tissue_properties_1 ON tab_expression_data_tissue_properties(tissue)",
  "CREATE INDEX ri_expression_data_values_1 ON tab_expression_data_values(variant_id)",
  "CREATE INDEX ri_expression_data_values_3 ON tab_expression_data_values(data_source_id)",
  "CREATE INDEX ri_gene_names_1 ON tab_gene_names(gene_id)",
  "CREATE INDEX ri_gene_names_2 ON tab_gene_names(name_type)",
  "CREATE INDEX ri_gene_variants_1 ON tab_gene_variants(gene_id)",
  "CREATE INDEX tab_expression_data_unitstab_expression_data_values ON tab_expression_data_values(unit)"
)

#### Set the Views  for the PK-Sim expression data base (enables quick result generation) ####
VIEW_TABLE <- list(
  QRY_CONTAINER_TISSUE = "CREATE VIEW QRY_CONTAINER_TISSUE AS SELECT TAB_CONTAINER_TISSUE.CONTAINER as CONTAINER, TAB_CONTAINER_TISSUE.TISSUE as TISSUE FROM TAB_CONTAINER_TISSUE",
  QRY_COUNT_GENES = "CREATE VIEW QRY_COUNT_GENES AS SELECT Count(TAB_GENES.GENE_ID) AS CountOfGENE_ID FROM TAB_GENES",
  QRY_COUNT_VALUES = "CREATE VIEW QRY_COUNT_VALUES AS SELECT Count(TAB_EXPRESSION_DATA_VALUES.VARIANT_ID) AS CountOfVARIANT_ID FROM TAB_EXPRESSION_DATA_VALUES",
  QRY_COUNT_VARIANTS = "CREATE VIEW QRY_COUNT_VARIANTS AS SELECT Count(TAB_GENE_VARIANTS.VARIANT_ID) AS CountOfVARIANT_ID FROM TAB_GENE_VARIANTS",
  QRY_GENDER_HINT = "CREATE VIEW QRY_GENDER_HINT AS SELECT TAB_EXPRESSION_DATA_GENDERS.GENDER, TAB_EXPRESSION_DATA_GENDERS.INFORMATION FROM TAB_EXPRESSION_DATA_GENDERS",
  QRY_HEALTH_STATE_HINT = "CREATE VIEW QRY_HEALTH_STATE_HINT AS SELECT TAB_EXPRESSION_DATA_HEALTH_STATE.HEALTH_STATE, TAB_EXPRESSION_DATA_HEALTH_STATE.INFORMATION FROM TAB_EXPRESSION_DATA_HEALTH_STATE",
  QRY_NAME_TYPE_HINT = "CREATE VIEW QRY_NAME_TYPE_HINT AS SELECT TAB_GENE_NAME_TYPES.NAME_TYPE, TAB_GENE_NAME_TYPES.INFORMATION FROM TAB_GENE_NAME_TYPES",
  QRY_SAMPLE_SOURCE_HINT = "CREATE VIEW QRY_SAMPLE_SOURCE_HINT AS SELECT TAB_EXPRESSION_DATA_SAMPLE_SOURCES.SAMPLE_SOURCE, TAB_EXPRESSION_DATA_SAMPLE_SOURCES.INFORMATION FROM TAB_EXPRESSION_DATA_SAMPLE_SOURCES",
  QRY_TISSUE_HINT = "CREATE VIEW QRY_TISSUE_HINT AS SELECT TAB_EXPRESSION_DATA_TISSUES.TISSUE, TAB_EXPRESSION_DATA_TISSUES.INFORMATION FROM TAB_EXPRESSION_DATA_TISSUES",
  QRY_UNIT_HINT = "CREATE VIEW QRY_UNIT_HINT AS SELECT TAB_EXPRESSION_DATA_UNITS.UNIT, TAB_EXPRESSION_DATA_UNITS.INFORMATION FROM TAB_EXPRESSION_DATA_UNITS"
)

#### List of table names, SQL creation, column type ####
# list data base table creation commands with additional information on variables and connections
CREATE_TABLE <- list(
  TAB = c(
    "tab_container_tissue",
    "tab_dts_properties",
    "tab_expression_data_age_properties",
    "tab_expression_data_ages",
    "tab_expression_data_bases",
    "tab_expression_data_gender_properties",
    "tab_expression_data_genders",
    "tab_expression_data_health_state",
    "tab_expression_data_health_state_properties",
    "tab_expression_data_properties",
    "tab_expression_data_records",
    "tab_expression_data_sample_source_properties",
    "tab_expression_data_sample_sources",
    "tab_expression_data_tissue_properties",
    "tab_expression_data_tissues",
    "tab_expression_data_units",
    "tab_expression_data_values",
    "tab_gene_name_types",
    "tab_gene_names",
    "tab_gene_variants",
    "tab_genes",
    "tab_global_statistics"
  ),
  COMMAND = c(
    "CREATE TABLE tab_container_tissue ( container TEXT NOT NULL, tissue TEXT NULL )",
    "CREATE TABLE tab_dts_properties ( table_name TEXT NOT NULL, column_name TEXT NOT NULL, german TEXT NULL, english TEXT NULL, tooltip_german TEXT NULL, tooltip_english TEXT NULL, dimension_type TEXT NULL, hidden BIGINT NOT NULL DEFAULT 0, editable BIGINT NOT NULL DEFAULT 1, PRIMARY KEY(table_name, column_name) )",
    "CREATE TABLE tab_expression_data_age_properties ( age_id BIGINT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(age_id, property, property_value), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )",
    "CREATE TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age TEXT, age_min DOUBLE, age_max DOUBLE, age_mean DOUBLE, age_median DOUBLE, PRIMARY KEY (age_id) )", "CREATE TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    # "CREATE TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age_min DOUBLE, age_max DOUBLE, age_mean DOUBLE, age_median DOUBLE, PRIMARY KEY (age_id) )", "CREATE TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    # "CREATE TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age_value TEXT, PRIMARY KEY (age_id) )", "CREATE TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    "CREATE TABLE tab_expression_data_gender_properties ( gender TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(gender, property, property_value), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender) )",
    "CREATE TABLE tab_expression_data_genders ( gender TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(gender) )",
    "CREATE TABLE tab_expression_data_health_state ( health_state TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(health_state) )",
    "CREATE TABLE tab_expression_data_health_state_properties ( health_state TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(health_state, property, property_value), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state) )",
    "CREATE TABLE tab_expression_data_properties ( data_source_id BIGINT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(data_source_id, property), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id) )",
    "CREATE TABLE tab_expression_data_records ( data_source_id BIGINT NOT NULL, data_base TEXT NOT NULL, data_base_rec_id TEXT NULL, last_refresh_date TEXT NOT NULL, gender TEXT NULL, tissue TEXT NULL, health_state TEXT NULL, sample_source TEXT NULL, age_id BIGINT NULL, PRIMARY KEY(data_source_id), FOREIGN KEY(data_base) REFERENCES tab_expression_data_bases(data_base), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )",
    "CREATE TABLE tab_expression_data_sample_source_properties ( sample_source TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(sample_source, property, property_value), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source) )",
    "CREATE TABLE tab_expression_data_sample_sources ( sample_source TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(sample_source) )",
    "CREATE TABLE tab_expression_data_tissue_properties ( tissue TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(tissue, property, property_value), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue) )",
    "CREATE TABLE tab_expression_data_tissues ( tissue TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(tissue) )",
    "CREATE TABLE tab_expression_data_units ( unit TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(unit) )",
    "CREATE TABLE tab_expression_data_values ( variant_id BIGINT NOT NULL, data_source_id BIGINT NOT NULL, sample_count DOUBLE NOT NULL, total_count DOUBLE NOT NULL, unit TEXT NOT NULL, PRIMARY KEY(variant_id, data_source_id), FOREIGN KEY(variant_id) REFERENCES tab_gene_variants(variant_id), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id), FOREIGN KEY(unit) REFERENCES tab_expression_data_units(unit) )",
    "CREATE TABLE tab_gene_name_types ( name_type TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(name_type) )",
    "CREATE TABLE tab_gene_names ( gene_id BIGINT NOT NULL, gene_name TEXT NOT NULL, name_type TEXT NOT NULL, PRIMARY KEY(gene_id, gene_name, name_type), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id), FOREIGN KEY(name_type) REFERENCES tab_gene_name_types(name_type) )",
    "CREATE TABLE tab_gene_variants ( variant_id BIGINT NOT NULL, variant_name TEXT NOT NULL, gene_id BIGINT NOT NULL, PRIMARY KEY(variant_id), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id) )",
    "CREATE TABLE tab_genes ( gene_id BIGINT NOT NULL, PRIMARY KEY(gene_id) )",
    "CREATE TABLE tab_global_statistics ( unit TEXT NULL, 'avg' DOUBLE NULL )"
  ),
  ALTER_COMMAND = c(
    "ALTER TABLE tab_container_tissue ( container TEXT NOT NULL, tissue TEXT NULL )",
    "ALTER TABLE tab_dts_properties ( table_name TEXT NOT NULL, column_name TEXT NOT NULL, german TEXT NULL, english TEXT NULL, tooltip_german TEXT NULL, tooltip_english TEXT NULL, dimension_type TEXT NULL, hidden BIGINT NOT NULL DEFAULT 0, editable BIGINT NOT NULL DEFAULT 1, PRIMARY KEY(table_name, column_name) )",
    "ALTER TABLE tab_expression_data_age_properties ( age_id BIGINT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(age_id, property, property_value), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )",
    "ALTER TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age TEXT, age_min DOUBLE, age_max DOUBLE, age_mean DOUBLE, age_median DOUBLE, PRIMARY KEY (age_id) )", "ALTER TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    # "ALTER TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age_min DOUBLE, age_max DOUBLE, age_mean DOUBLE, age_median DOUBLE, PRIMARY KEY (age_id) )", "ALTER TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    # "ALTER TABLE tab_expression_data_ages ( age_id BIGINT NOT NULL, age_value TEXT, PRIMARY KEY (age_id) )", "ALTER TABLE tab_expression_data_bases ( data_base TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(data_base) )",
    "ALTER TABLE tab_expression_data_gender_properties ( gender TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(gender, property, property_value), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender) )",
    "ALTER TABLE tab_expression_data_genders ( gender TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(gender) )",
    "ALTER TABLE tab_expression_data_health_state ( health_state TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(health_state) )",
    "ALTER TABLE tab_expression_data_health_state_properties ( health_state TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(health_state, property, property_value), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state) )",
    "ALTER TABLE tab_expression_data_properties ( data_source_id BIGINT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(data_source_id, property), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id) )",
    "ALTER TABLE tab_expression_data_records ( data_source_id BIGINT NOT NULL, data_base TEXT NOT NULL, data_base_rec_id TEXT NULL, last_refresh_date TEXT NOT NULL, gender TEXT NULL, tissue TEXT NULL, health_state TEXT NULL, sample_source TEXT NULL, age_id BIGINT NULL, PRIMARY KEY(data_source_id), FOREIGN KEY(data_base) REFERENCES tab_expression_data_bases(data_base), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source), FOREIGN KEY(gender) REFERENCES tab_expression_data_genders(gender), FOREIGN KEY(health_state) REFERENCES tab_expression_data_health_state(health_state), FOREIGN KEY(age_id) REFERENCES tab_expression_data_ages(age_id) )",
    "ALTER TABLE tab_expression_data_sample_source_properties ( sample_source TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(sample_source, property, property_value), FOREIGN KEY(sample_source) REFERENCES tab_expression_data_sample_sources(sample_source) )",
    "ALTER TABLE tab_expression_data_sample_sources ( sample_source TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(sample_source) )",
    "ALTER TABLE tab_expression_data_tissue_properties ( tissue TEXT NOT NULL, property TEXT NOT NULL, property_value TEXT NOT NULL, PRIMARY KEY(tissue, property, property_value), FOREIGN KEY(tissue) REFERENCES tab_expression_data_tissues(tissue) )",
    "ALTER TABLE tab_expression_data_tissues ( tissue TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(tissue) )",
    "ALTER TABLE tab_expression_data_units ( unit TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(unit) )",
    "ALTER TABLE tab_expression_data_values ( variant_id BIGINT NOT NULL, data_source_id BIGINT NOT NULL, sample_count DOUBLE NOT NULL, total_count DOUBLE NOT NULL, unit TEXT NOT NULL, PRIMARY KEY(variant_id, data_source_id), FOREIGN KEY(variant_id) REFERENCES tab_gene_variants(variant_id), FOREIGN KEY(data_source_id) REFERENCES tab_expression_data_records(data_source_id), FOREIGN KEY(unit) REFERENCES tab_expression_data_units(unit) )",
    "ALTER TABLE tab_gene_name_types ( name_type TEXT NOT NULL, information TEXT NOT NULL, PRIMARY KEY(name_type) )",
    "ALTER TABLE tab_gene_names ( gene_id BIGINT NOT NULL, gene_name TEXT NOT NULL, name_type TEXT NOT NULL, PRIMARY KEY(gene_id, gene_name, name_type), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id), FOREIGN KEY(name_type) REFERENCES tab_gene_name_types(name_type) )",
    "ALTER TABLE tab_gene_variants ( variant_id BIGINT NOT NULL, variant_name TEXT NOT NULL, gene_id BIGINT NOT NULL, PRIMARY KEY(variant_id), FOREIGN KEY(gene_id) REFERENCES tab_genes(gene_id) )",
    "ALTER TABLE tab_genes ( gene_id BIGINT NOT NULL, PRIMARY KEY(gene_id) )",
    "ALTER TABLE tab_global_statistics ( unit TEXT NULL, 'avg' DOUBLE NULL )"
  ),
  TYPE = list(
    c(container = "TEXT", tissue = "TEXT"),
    c(table_name = "TEXT", column_name = "TEXT", german = "TEXT", english = "TEXT", tooltip_german = "TEXT", tooltip_english = "TEXT", dimension_type = "TEXT", hidden = "BIGINT", editable = "BIGINT"),
    c(age_id = "BIGINT", property = "TEXT", property_value = "TEXT"),
    c(age_id = "BIGINT", age = "TEXT", age_min = "DOUBLE", age_max = "DOUBLE", age_median = "DOUBLE", age_mean = "DOUBLE"),
    # c("BIGINT", "TEXT", "TEXT"), # tab_expression_data_ages
    c(data_base = "TEXT", url = "TEXT"),
    c(gender = "TEXT", property = "TEXT", property_value = "TEXT"),
    c(gender = "TEXT", information = "TEXT"),
    c(health_state = "TEXT", information = "TEXT"),
    c(health_state = "TEXT", property = "TEXT", property_value = "TEXT"),
    c(data_source_id = "BIGINT", property = "TEXT", property_value = "TEXT"),
    c(data_source_id = "BIGINT", data_base_rec_id = "TEXT", tissue = "TEXT", health_state = "TEXT", gender = "TEXT", sample_source = "TEXT", data_base = "TEXT", last_refresh_date = "TEXT", age_id = "BIGINT"),
    c(property_value = "TEXT", property = "TEXT", sample_source = "TEXT"),
    c(sample_source = "TEXT", information = "TEXT"),
    c(tissue = "TEXT", property_value = "TEXT", property = "TEXT"),
    c(tissue = "TEXT", information = "TEXT"),
    c(unit = "TEXT", information = "TEXT"),
    c(variant_id = "BIGINT", data_source_id = "BIGINT", sample_count = "DOUBLE", total_count = "DOUBLE", unit = "TEXT"),
    c(name_type = "TEXT", information = "TEXT"),
    c(gene_id = "BIGINT", name_type = "TEXT", gene_name = "TEXT"),
    c(gene_id = "BIGINT", variant_name = "TEXT", variant_id = "BIGINT"),
    c(gene_id = "BIGINT"),
    c(unit = "TEXT", avg = "DOUBLE")
  )
)
